#!/bin/bash
#============================================================
# https://github.com/P3TERX/Actions-OpenWrt
# File name: diy-part2.sh
# Description: OpenWrt DIY script part 2 (After Update feeds)
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#============================================================

# Modify default IP
sed -i 's/192.168.1.1/192.168.123.2/g' package/base-files/files/bin/config_generate
sed -i 's/services/vpn/g' feeds/luci/applications/luci-app-openvpn/luasrc/controller/openvpn.lua
sed -i 's/services/vpn/g' feeds/luci/applications/luci-app-openvpn/luasrc/model/cbi/openvpn.lua
sed -i 's/services/vpn/g' feeds/luci/applications/luci-app-openvpn/luasrc/view/openvpn/pageswitch.htm
sed -i 's/services/vpn/g' feeds/helloworld/luci-app-ssr-plus/luasrc/controller/shadowsocksr.lua
sed -i 's/services/vpn/g' feeds/helloworld/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
sed -i 's/services/vpn/g' feeds/helloworld/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/servers.lua
sed -i 's/services/vpn/g' feeds/helloworld/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/server.lua
sed -i 's/services/vpn/g' feeds/helloworld/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/server-config.lua
sed -i 's/services/vpn/g' feeds/helloworld/luci-app-ssr-plus/luasrc/view/shadowsocksr/check.htm
sed -i 's/services/vpn/g' feeds/helloworld/luci-app-ssr-plus/luasrc/view/shadowsocksr/checkport.htm
sed -i 's/services/vpn/g' feeds/helloworld/luci-app-ssr-plus/luasrc/view/shadowsocksr/refresh.htm
sed -i 's/services/vpn/g' feeds/helloworld/luci-app-ssr-plus/luasrc/view/shadowsocksr/server_list.htm
sed -i 's/services/vpn/g' feeds/helloworld/luci-app-ssr-plus/luasrc/view/shadowsocksr/status.htm
sed -i 's/services/vpn/g' feeds/helloworld/luci-app-ssr-plus/luasrc/view/shadowsocksr/subscribe.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/controller/clash.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/model/cbi/clash/config/config.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/model/cbi/clash/config/create.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/model/cbi/clash/config/groups.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/model/cbi/clash/config/import.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/model/cbi/clash/config/ip-rules.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/model/cbi/clash/config/proxy_provider.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/model/cbi/clash/config/rule_provider.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/model/cbi/clash/config/ruleprovider_manager.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/model/cbi/clash/config/rules.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/model/cbi/clash/config/servers-config.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/model/cbi/clash/dns/advance.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/model/cbi/clash/dns/dns.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/model/cbi/clash/dns/port.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/model/cbi/clash/game/game-rule.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/model/cbi/clash/game/game-settings.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/model/cbi/clash/other.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/view/clash/conf.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/view/clash/core_check.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/view/clash/game_rule.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/view/clash/geoip.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/view/clash/list.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/view/clash/rulep.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/view/clash/start_stop.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/view/clash/status.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/view/clash/status_log.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-clash/luasrc/view/clash/update.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-openclash/files/usr/lib/lua/luci/controller/openclash.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-openclash/files/usr/lib/lua/luci/model/cbi/openclash/client.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-openclash/files/usr/lib/lua/luci/model/cbi/openclash/config.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-openclash/files/usr/lib/lua/luci/model/cbi/openclash/config-subscribe.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-openclash/files/usr/lib/lua/luci/model/cbi/openclash/game-rules-manage.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-openclash/files/usr/lib/lua/luci/model/cbi/openclash/groups-config.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-openclash/files/usr/lib/lua/luci/model/cbi/openclash/log.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-openclash/files/usr/lib/lua/luci/model/cbi/openclash/proxy-provider-config.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-openclash/files/usr/lib/lua/luci/model/cbi/openclash/rule-providers-config.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-openclash/files/usr/lib/lua/luci/model/cbi/openclash/rule-providers-manage.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-openclash/files/usr/lib/lua/luci/model/cbi/openclash/rule-providers-settings.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-openclash/files/usr/lib/lua/luci/model/cbi/openclash/servers.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-openclash/files/usr/lib/lua/luci/model/cbi/openclash/servers-config.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-openclash/files/usr/lib/lua/luci/model/cbi/openclash/settings.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-openclash/files/usr/lib/lua/luci/view/openclash/download_rule.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-openclash/files/usr/lib/lua/luci/view/openclash/server_list.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-openclash/files/usr/lib/lua/luci/view/openclash/state.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-openclash/files/usr/lib/lua/luci/view/openclash/status.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-openclash/files/usr/lib/lua/luci/view/openclash/switch_mode.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-openclash/files/usr/lib/lua/luci/view/openclash/update.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/controller/passwall.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/model/cbi/passwall/server/index.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/model/cbi/passwall/server/user.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/model/cbi/passwall/node_config.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/model/cbi/passwall/node_list.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/model/cbi/passwall/node_subscribe.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/model/cbi/passwall/rule.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/model/cbi/passwall/shunt_rules.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/model/cbi/passwall/client/node_config.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/model/cbi/passwall/client/node_list.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/model/cbi/passwall/client/node_subscribe.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/model/cbi/passwall/client/rule.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/model/cbi/passwall/client/shunt_rules.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/view/passwall/app_update/brook_version.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/view/passwall/app_update/kcptun_version.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/view/passwall/app_update/trojan_go_version.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/view/passwall/app_update/v2ray_version.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/view/passwall/global/footer.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/view/passwall/global/status.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/view/passwall/global/status2.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/view/passwall/global/tips.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/view/passwall/haproxy/status.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/view/passwall/log/log.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/view/passwall/node_list/link_add_node.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/view/passwall/node_list/link_share_man.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/view/passwall/node_list/node_list.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/view/passwall/rule/rule_version.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/view/passwall/server/log.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-passwall/luasrc/view/passwall/server/users_list_status.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-ssr-plus/luasrc/controller/shadowsocksr.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/servers.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/server.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/server-config.lua
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-ssr-plus/luasrc/view/shadowsocksr/check.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-ssr-plus/luasrc/view/shadowsocksr/checkport.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-ssr-plus/luasrc/view/shadowsocksr/refresh.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-ssr-plus/luasrc/view/shadowsocksr/server_list.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-ssr-plus/luasrc/view/shadowsocksr/status.htm
sed -i 's/services/vpn/g' feeds/kenzo/luci-app-ssr-plus/luasrc/view/shadowsocksr/subscribe.htm
sed -i 's/services/vpn/g' feeds/jerryk/luci-app-vssr/luasrc/controller/vssr.lua
sed -i 's/services/vpn/g' feeds/jerryk/luci-app-vssr/luasrc/model/cbi/vssr/advanced.lua
sed -i 's/services/vpn/g' feeds/jerryk/luci-app-vssr/luasrc/model/cbi/vssr/client-config.lua
sed -i 's/services/vpn/g' feeds/jerryk/luci-app-vssr/luasrc/model/cbi/vssr/server.lua
sed -i 's/services/vpn/g' feeds/jerryk/luci-app-vssr/luasrc/model/cbi/vssr/server-config.lua
sed -i 's/services/vpn/g' feeds/jerryk/luci-app-vssr/luasrc/model/cbi/vssr/servers.lua
sed -i 's/services/vpn/g' feeds/jerryk/luci-app-vssr/luasrc/view/vssr/refresh.htm
sed -i 's/services/vpn/g' feeds/jerryk/luci-app-vssr/luasrc/view/vssr/ssrurl.htm
sed -i 's/services/vpn/g' feeds/jerryk/luci-app-vssr/luasrc/view/vssr/status_bottom.htm
sed -i 's/services/vpn/g' feeds/jerryk/luci-app-vssr/luasrc/view/vssr/status_top.htm
sed -i 's/services/vpn/g' feeds/jerryk/luci-app-vssr/luasrc/view/vssr/tblsection.htm
sed -i 's/services/vpn/g' feeds/jerryk/luci-app-vssr/luasrc/view/vssr/update_subscribe.htm
